name: ci

on: push

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint checks (flake8)
        run: |
          pip install flake8
          flake8 app.py test_app.py

      - name: Run Flask App (for test)
        run: |
          nohup python app.py &
          sleep 5  # Give server time to start
          curl -f http://127.0.0.1:5000/health
